export enum statusFechamentoReinf{

    POSICAO_NULA = 0,
	ABERTO = 1,
	AGUARDANDO_ENVIO = 2,
	AGUARDANDO_PROCESSAMENTO = 3,
	PROCESSADO = 4,
	RECUSADO = 5,
	REABERTURA_PERIODO = 6,
	ERRO = 7,
	ERRO_VALIDACAO = 8,
}